#!/usr/bin/env bash
# script that adds a users contact details to a listing

echo "New contact"

while true
do
	echo "First Name: "
	read -r first_name
	if [[ "$first_name" =~ ([^[:alpha:]+]) ]]
	then
		echo "There are no characters or numbers permitted."
	else
		break	
	fi
done

while true
do
	echo "Last Name: "
	read -r last_name
	if [[ "$last_name" =~ ([^[:alpha:]+]) ]]
	then
		echo "There are no characters or numbers permitted."
	else
		break
	fi
done

while true
do
	echo "Mobile number: "
	read -r mobile
	if [[ "$mobile" =~ ^\d{10}$ ]]
	then
		break
	else
		echo "Can only be digits 0 to 9."
	fi
done

echo "${first_name^^},${last_name^^},${mobile}" >> listing
