#!/usr/bin/env bash
# script that adds a users contact details to a listing

echo "New contact"

while true
do
	echo "First Name: "
	read -r first_name
	if [[ "$first_name" =~ ([^[:alpha:]+]) ]]
	then
		echo "There are no characters or numbers permitted."
	else
		break	
	fi
done

while true
do
	echo "Last Name: "
	read -r last_name
	if [[ "$last_name" =~ ([^[:alpha:]+]) ]]
	then
		echo "There are no characters or numbers permitted."
	else
		break
	fi
done

while true
do
	echo "Mobile number: "
	read -r mobile
	echo "$mobile"
	if [[ "$mobile | grep -e ^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$" ]]
	then
		echo "Can only be digits 0 to 9."
	else
		break
	fi
done

echo "${first_name^^},${last_name^^},${mobile}" >> listing
